version: "3.8"

services:
  location-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: location-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
